### ISSUE TITLE
Figma - login

### ISSUE THREAD

**Issue by patelmilanun** [nvshare/nvshare#1]
Create a figma design for login page with following functionality

- Continue with github and google

**Comment by patelmilanun** [comment]
https://www.figma.com/file/hecr9xQioseqv1jHJFsCU6/NV-Share?type=design&node-id=354-10004&mode=design&t=IaV3fcWZl2LsGkid-0

**Comment by AshishBarvaliya** [comment]
@patelmilanun looks good. works for now
